### PR TITLE
European deliveries query fix

### PR DESCRIPTION
**Pull request by mbrentini**

### CODE REVIEW

**Comment by mbrentini** [comment]
Hi @Quetzacoalt91 

I'm sorry again, this PR aims to enable european deliveries export, the name of carrier in the query was wrong...

Thank you

**Comment by Quetzacoalt91** [comment]
Please check that you do not have another fix to apply. Merging a PR cost me some time that I cannot give for only one module.

Thanks

**Comment by mbrentini** [comment]
This should be the last PR, next time i'll group the modifications for a period and push fewer PRs, promised !

**Comment by Quetzacoalt91** [comment]
Great, thanks ! This PR has just been merged and the changes should be available soon

Regards

**Pull request merged**
