### PR TITLE
Critical fixes

### PR DESCRIPTION
**Pull request by mbrentini**
Hi @Quetzacoalt91 

I just found a bug for customers on One Page Checkout mode, Pickup and Predict selections couldn't be saved in DB.

Thank you for your patience :octocat:

### CODE REVIEW

**Comment by mbrentini** [comment]
Hi @Quetzacoalt91 

Please don't merge it yet, i have some modifications to push before

Thank you

**Comment by Quetzacoalt91** [comment]
Okay, let me know when it is done.

Regards

**Comment by mbrentini** [comment]
Hi @Quetzacoalt91 

Should I increment the version to 5.1.2 ?

Thanks

**Comment by Quetzacoalt91** [comment]
Hi,

Yes you can. We are not the only one who can choose the new module version. It can be set on your side.

**Comment by mbrentini** [comment]
Hi @Quetzacoalt91 

You can merge this PR now :)

Thank you! :+1:

**Pull request merged**
